
[ennoia]
name = "Ennoia"
desc = "Game framework"
type = "lib"
version = "0.1.0"
file = "src/"


[ennoia-tests]
name = "Ennoia Tests"
type = "test"
file = "tests/"
dependencies = [
  "SDL3-link",
  "spng-link",
  "GL-link",
  "GLEW-link",
  "ennoia-link"
]

